parameters:
#    ktap_backend.example.class: Ktap\BackendBundle\Example

services:
#    ktap_backend.example:
#        class: %ktap_backend.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
