Ktap\UserBundle\Entity\User:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: email    
    properties:
        email:
            - Email:
                message: The email "{{ value }}" is not a valid email.
                checkMX: true